### PR TITLE
Merge pull request #1 from cwru-robotics/master

### PR DESCRIPTION
**Pull request by xpharry**
update for 476 class

### CODE REVIEW

**Comment by xpharry** [comment]
update

**Comment by xpharry** [comment]
update

**Comment by lucbettaieb** [comment]
What was this for?

**Comment by xpharry** [comment]
Forget it. I have canceled it. Sorry for bothering. Peng Sent from Netease Mail On 2016-03-02 18:40 , Luc Bettaieb Wrote: What was this for? — Reply to this email directly or view it on GitHub.

**Comment by lucbettaieb** [comment]
No problemo.

**Pull request closed without merging**
